package cz.smartfine.pc.view;

import cz.smartfine.pc.SFPCClient;
import cz.smartfine.pc.networklayer.dataprotocols.LoginProtocol;

/**
 * Panel pro odhlášení PC klienta od serveru.
 * @author Pavel Brož
 */
public class LogoutPanel extends javax.swing.JPanel {

    /**
     * Posluchač události odhlášení.
     */
    private ILogoutListener listener;
    /**
     * Login protokol.
     */
    private LoginProtocol loginProtocol;

    //================================================== KONSTRUKTORY & DESTRUKTORY ==================================================//
    
    /**
     * Konstruktor.
     */
    public LogoutPanel() {
        initComponents();
    }

    /**
     * Konstruktor.
     * @param listener Posluchač události odhlášení.
     */
    public LogoutPanel(ILogoutListener listener) {
        this();
        this.listener = listener;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butLogout = new javax.swing.JButton();

        butLogout.setText(SFPCClient.getApplication().getLocalization().getString("logoutpanel.logoutbut.text"));
        butLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(butLogout)
                .addContainerGap(291, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(butLogout)
                .addContainerGap(266, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    //================================================== UI HANDLERY ==================================================//
    
    /**
     * Odhlašuje ze serveru.
     * @param evt 
     */
    private void butLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLogoutActionPerformed
        loginProtocol = new LoginProtocol(SFPCClient.getApplication().getConnectionProvider().getNetworkInterface());
        loginProtocol.logoutFromServer();
        
        if (listener != null){
            listener.onLogout();
        }
    }//GEN-LAST:event_butLogoutActionPerformed

    //================================================== UI PRVKY ==================================================//
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butLogout;
    // End of variables declaration//GEN-END:variables

}
